env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
rules: {
  import/prefer-default-export: off,
  '@typescript-eslint/no-unused-vars': off,
  import/no-dynamic-require: off,
  global-require: off,
  no-console: off,
  consistent-return: off,
  '@typescript-eslint/no-shadow': off,
}
