name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@simula-labs'

      - run: |
          npm ci
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_DEVELOPER_PAT }}
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_DEVELOPER_PAT }}
          NPM_TOKEN: ${{ secrets.GH_DEVELOPER_PAT }}